# Jekyll configuration for GitHub Pages
title: Homemade piPhone
description: A homemade smartphone powered by Raspberry Pi
theme: jekyll-theme-minimal

# GitHub Pages settings
plugins:
  - jekyll-relative-links

# Relative links configuration
relative_links:
  enabled: true
  collections: true

# Markdown processing
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
